version: '3'

services:
  client:
    build:
      context: ./src/client
    ports:
      - '3000:3000'
  server:
    build:
      context: ./src/server
    depends_on:
      - database
    ports:
      - '5001:5001'
  database:
    image: postgres:13.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7007
      POSTGRES_DB: dbnews