version: '3'
services:
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile

    ports:
      - '3000:3000'
  backend-server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '5000:5001'
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 7007
      POSTGRES_USER: postgres
      POSTGRES_DB: dbnews